name: Java CI with Apache Ant

on:
  push:
    branches: [ devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Ant
        run: |
          hash=$(echo "${{ github.sha }}" | sed -e 's/\(.\{7\}\).*/\1/')
          sed -i "s/\(app_version\s*=\s*v\?[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?\).*/\1-$(date +%Y%m%d) (${hash})/" src/nearinfinity.properties
          sed -i 's/debug="false"/debug="true"/' build.xml
          ant -noinput -buildfile build.xml
      - name: Upload artifact
        if: ${{ github.repository == 'Argent77/NearInfinity' }}
        uses: pyTooling/Actions/releaser@r2
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: NearInfinity.jar
